package fileexplorer.gui.forms;

import javax.swing.SwingUtilities;

@Deprecated 
public class ProgressIndeterminate extends javax.swing.JFrame {

	static {
		init();
	}
	
	/**
	 * Creates new form ProgressIndeterminate
	 */
	public ProgressIndeterminate() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jProgressBar1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jProgressBar1.setForeground(java.awt.Color.white);
        jProgressBar1.setIndeterminate(true);
        jProgressBar1.setString("Processing...");
        jProgressBar1.setStringPainted(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

	private static ProgressIndeterminate frame;
	
	private static void init() {	
		/* Create and display the form */
		SwingUtilities.invokeLater(new Runnable() {
//		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {				
				System.out.println("  // starting ProgressIndeterminate...");
				frame = new ProgressIndeterminate();
			}
		});
	}
	
	public static void start() {
		System.out.println("  // showing ProgressIndeterminate... isnull=" + (frame==null));
//		init();
		if(frame != null)
			frame.setVisible(true);
	}
	
	public static void stop() {
		System.out.println("  // hiding ProgressIndeterminate... isnull=" + (frame==null));
//		frame.dispose();
		if(frame != null)
			frame.setVisible(false);
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
