/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.mytests;

import gui.mytests.SystemResources.IconRegistry;
import gui.mytests.handlers.BookmarkedItem;
import gui.mytests.handlers.fs.FileAttributes;
import gui.mytests.handlers.fs.FileSystemHandler;
import gui.mytests.handlers.fs.LocalFileSystemHandler;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Icon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class FilePropertiesForm extends javax.swing.JFrame {

	private FileAttributes[] files;
	private FileSystemHandler fileSystemHandler;
	
	/**
	 * Creates new form PropertiesForm
	 * @param icon If multiples files are specified then this parameter has no 
	 *		significance as a constant icon will be used.
	 * @param type If multiples files are specified then this parameter has no 
	 *		significance as a constant icon will be used.
	 */
	public FilePropertiesForm(final FileAttributes[] files, final Icon icon, final String type, final FileSystemHandler fsHandler) {
		this.files = files;
		this.fileSystemHandler = fsHandler;
		initComponents();
		
		// set values to GUI components
		if(files.length == 1) {
			lblTypeIcon.setIcon(icon);
			txtName.setText(type.equals(BookmarkedItem.ItemType.SYS_DRIVE.toString()) ? files[0].absolutePath : files[0].name); 
				txtName.setCaretPosition(0);			
			txtType.setText(type); 
				txtType.setCaretPosition(0);
			txtSize.setText(files[0].sizeInWords + " (" + files[0].size + " B)"); 
				txtSize.setCaretPosition(0);
			txtLastModified.setText(files[0].lastModifiedDateString); 
				txtLastModified.setCaretPosition(0);
			chkReadable.setSelected(files[0].isReadable);
			chkWritable.setSelected(files[0].isWritable);
			chkExecutable.setSelected(files[0].isExecutable);
			chkHidden.setSelected(files[0].isHidden);
		} else {
			lblTypeIcon.setIcon(IconRegistry.multipleFilesIcon_big);
			
			StringBuilder names = new StringBuilder();
			List<String> types = new ArrayList<>();
			long totalSize = 0L;
			long minLastModified = files[0].lastModified, maxLastModified = files[0].lastModified;
			for(FileAttributes file : files) {
				names.append(file.name).append("; ");
				if(!types.contains(file.type))
					types.add(file.type);
				totalSize += file.size;
				minLastModified = Math.min(file.lastModified, minLastModified);
				maxLastModified = Math.max(file.lastModified, maxLastModified);
			}
			
			txtName.setText(names.toString()); 
				txtName.setCaretPosition(0);
			StringBuilder tmpTypes = new StringBuilder();
			for(String ftype : types)
				tmpTypes.append(ftype).append("; ");
			txtType.setText(tmpTypes.toString());
				txtType.setCaretPosition(0);
			txtSize.setText(FileAttributes.getSizeInWords(totalSize) + " (" + totalSize + " B)"); 
				txtSize.setCaretPosition(0);
			txtLastModified.setText(	FileAttributes.getlastModifiedDateString(minLastModified) + 
										" - " + 
										FileAttributes.getlastModifiedDateString(maxLastModified)); 
			txtLastModified.setCaretPosition(0);
		}
		
		// global values
		txtPath.setText(files[0].absolutePath); 
			txtPath.setCaretPosition(0);
		txtLocation.setText(files[0].isLocal ? "Local" : "Remote"); 
			txtLocation.setCaretPosition(0);
 	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTypeIcon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        chkReadable = new javax.swing.JCheckBox();
        chkWritable = new javax.swing.JCheckBox();
        chkExecutable = new javax.swing.JCheckBox();
        chkHidden = new javax.swing.JCheckBox();
        btnCancel = new javax.swing.JButton();
        btnApply = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        txtType = new javax.swing.JTextField();
        txtPath = new javax.swing.JTextField();
        txtLocation = new javax.swing.JTextField();
        txtSize = new javax.swing.JTextField();
        txtLastModified = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Properties");
        setAlwaysOnTop(true);
        setResizable(false);

        jLabel1.setText("Name:");

        jLabel2.setText("Path:");

        jLabel3.setText("Type:");

        jLabel4.setText("Location:");

        jLabel5.setText("Size:");

        jLabel6.setText("Last modified:");

        jLabel7.setText("Permissions:");

        chkReadable.setText("Readable");

        chkWritable.setText("Writable");

        chkExecutable.setText("Executable");

        chkHidden.setText("Hidden");

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnApply.setText("Apply");
        btnApply.setMaximumSize(new java.awt.Dimension(65, 23));
        btnApply.setMinimumSize(new java.awt.Dimension(65, 23));
        btnApply.setPreferredSize(new java.awt.Dimension(65, 23));
        btnApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyActionPerformed(evt);
            }
        });

        btnOK.setText("OK");
        btnOK.setMaximumSize(new java.awt.Dimension(65, 23));
        btnOK.setMinimumSize(new java.awt.Dimension(65, 23));
        btnOK.setPreferredSize(new java.awt.Dimension(65, 23));
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        txtType.setEditable(false);

        txtPath.setEditable(false);

        txtLocation.setEditable(false);

        txtSize.setEditable(false);

        txtLastModified.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTypeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtName))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPath, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLocation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnApply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(chkReadable)
                                .addGap(18, 18, 18)
                                .addComponent(chkWritable)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chkExecutable)
                                .addGap(18, 18, 18)
                                .addComponent(chkHidden)
                                .addGap(2, 2, 2))
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addComponent(txtLastModified, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTypeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtLastModified, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(chkReadable)
                    .addComponent(chkWritable)
                    .addComponent(chkExecutable)
                    .addComponent(chkHidden))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel)
                    .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        lblTypeIcon.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
		if(saveValues())
			form.dispose();
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
		form.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyActionPerformed
		saveValues();
    }//GEN-LAST:event_btnApplyActionPerformed

	private boolean saveValues() throws IllegalArgumentException {
		/*
		String attributeToChange = null;
		boolean successful = true;
		
		try {
			attributeToChange = "name";
			String name = txtName.getText().trim();
			if(!name.equals(file.name)) {
//				fileSystemHandler.rename(file, name);
			}

			attributeToChange = "read bit";
			if(file.isReadable != chkReadable.isSelected()) {
//				fileSystemHandler.setReadable(chkReadable.isSelected());
			}

			attributeToChange = "write bit";
			if(file.isReadable != chkWritable.isSelected()) {
//				fileSystemHandler.setReadable(chkWritable.isSelected());
			}

			attributeToChange = "execute bit";
			if(file.isReadable != chkExecutable.isSelected()) {
//				fileSystemHandler.setReadable(chkExecutable.isSelected());
			}

			attributeToChange = "hidden bit";
			if(file.isReadable != chkHidden.isSelected()) {
//				fileSystemHandler.setReadable(txtHidden.isSelected());
			}
		} catch(Exception e) {
			if(JOptionPane.showConfirmDialog(this,
					"Cannot save attributes: " + attributeToChange + "\nRetry?", "Error changing attributes",
					JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
				successful = false;
			}
		}
		
		return successful;
		*/
		throw new UnsupportedOperationException("not yet designed");
	}
	
	private static FilePropertiesForm form = null;
	
	static FilePropertiesForm init(final FileAttributes[] files, final Icon icon, final String type, final FileSystemHandler fsHandler) {
		/* Set the predefined look and feel */ /*
		try {
			boolean lnfNameNotFound = true;
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if (SystemResources.LOOKnFEEL_NAMES.contains(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					lnfNameNotFound = false;
					break;
				}
			}
			if(lnfNameNotFound)
				System.err.println("Warning: Cannot set predefined L&F: " + SystemResources.LOOKnFEEL_NAMES); // log error
		} catch (Exception exc) {
			System.err.println("Error: Cannot set L&F: " + exc); // Log error
		}
		*/
		
		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				form = new FilePropertiesForm(files, icon, type, fsHandler);
				form.setVisible(true);
			}
		});
		
		return form;
	}
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApply;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JCheckBox chkExecutable;
    private javax.swing.JCheckBox chkHidden;
    private javax.swing.JCheckBox chkReadable;
    private javax.swing.JCheckBox chkWritable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTypeIcon;
    private javax.swing.JTextField txtLastModified;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPath;
    private javax.swing.JTextField txtSize;
    private javax.swing.JTextField txtType;
    // End of variables declaration//GEN-END:variables
}
